<template>
  <article class="cv-sheet ref-cv ref-ats-precision" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <header class="ref-ats-head" v-bind="editAttrs('profile')"><div><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><p>{{ profile.summary }}</p></div><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div></header>
    <div class="ref-ats-body"><main><section v-bind="editAttrs('experience','experience')"><h3>Experience</h3><div class="ref-ats-experience"><article v-for="job in profile.experience" :key="job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="bullet in job.bullets" :key="bullet">{{ bullet }}</li></ul></article></div></section><section v-if="profile.education?.length" v-bind="editAttrs('education','education')"><h3>Education</h3><div class="ref-education"><article v-for="item in profile.education" :key="item.title"><strong>{{ item.title }}</strong><span>{{ item.place }}</span><small>{{ item.period }}</small></article></div></section></main><aside><section v-bind="editAttrs('skills','skills')"><h3>Skills</h3><div class="ref-skills ref-ats-skills"><span v-for="skill in profile.skills" :key="skill">{{ skill }}</span></div></section><section v-bind="editAttrs('projects','projects')"><h3>Selected Projects</h3><div class="ref-projects ref-ats-projects"><article v-for="project in profile.projects.slice(0,2)" :key="project.name"><strong>{{ project.name }}</strong><small>{{ project.impact }}</small></article></div></section><section v-if="profile.certificates?.length" v-bind="editAttrs('education','certificates')"><h3>Certifications</h3><div class="ref-certificates"><article v-for="item in profile.certificates" :key="item.title"><strong>{{ item.title }}</strong><span>{{ item.issuer }}</span><small>{{ item.period }}</small></article></div></section></aside></div>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'AtsPrecisionTemplate', mixins:[referenceTemplateMixin] }
</script>