<template>
  <article class="cv-sheet ref-cv ref-brand-motion" :class="referenceAppearanceClasses" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <aside class="ref-brand-rail"><div class="ref-brand-avatar"><img v-if="profile.avatar" :src="profile.avatar" alt="" :style="avatarImageStyle"><span v-else>{{ initials }}</span></div><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div><blockquote>Brands grow when<br>people feel something.</blockquote><div v-bind="editAttrs('skills','skills')"><h3>Skills</h3><div class="ref-skills ref-brand-skills"><span v-for="(skill, skillIndex) in profile.skills" :key="skillIndex">{{ skill }}</span></div></div><div v-bind="editAttrs('languages','languages')"><h3>Languages</h3><div class="ref-brand-languages"><span v-for="(language, languageIndex) in profile.languages" :key="languageIndex">{{ language }}</span></div></div></aside>
    <main class="ref-brand-main"><header v-bind="editAttrs('profile')"><span>Ideas · People · Impact</span><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><p>{{ profile.summary }}</p><em>BRANDS<br>PEOPLE<br>STORIES<br>GROWTH</em></header><div class="ref-brand-metrics" v-bind="editAttrs('impact','highlights')"><div v-for="item in profile.highlights" :key="item.id || item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></div><section v-bind="editAttrs('experience','experience')"><h3>Work Experience</h3><div class="ref-brand-experience"><article v-for="job in profile.experience" :key="job.id || job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="(bullet, bulletIndex) in job.bullets" :key="bulletIndex">{{ bullet }}</li></ul></article></div></section><section v-bind="editAttrs('projects','projects')"><h3>Selected Campaigns</h3><div class="ref-projects ref-brand-projects"><article v-for="project in profile.projects.slice(0,3)" :key="project.id || project.name"><strong>{{ project.name }}</strong><small>{{ project.impact }}</small></article></div></section></main>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'BrandMotionTemplate', mixins:[referenceTemplateMixin] }
</script>