<template>
  <article class="cv-sheet ref-cv ref-insight-grid" :class="referenceAppearanceClasses" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <header class="ref-insight-head" v-bind="editAttrs('profile')"><div><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div></div><div class="ref-chart-bars"><i></i><i></i><i></i><i></i><i></i><strong>Turning Data<br>Into Decisions</strong></div></header>
    <section class="ref-insight-summary" v-bind="editAttrs('profile','summary')"><div><h3>Professional Summary</h3><p>{{ profile.summary }}</p></div><div v-if="visible('highlights')" class="ref-insight-metrics" v-bind="editAttrs('impact','highlights')"><div v-for="item in profile.highlights" :key="item.id || item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></div></section>
    <div class="ref-insight-grid-body"><section v-bind="editAttrs('skills','skills')"><h3>Core Skills</h3><div class="ref-skill-bars"><div v-for="(skill, index) in profile.skills" :key="index"><span>{{ skill }}</span><i><b :style="{ width: Math.max(62, 92-index*4)+'%' }"></b></i></div></div></section><section v-bind="editAttrs('projects','projects')"><h3>Key Achievements</h3><div class="ref-projects ref-insight-achievements"><article v-for="(project,index) in profile.projects" :key="project.id || project.name"><div class="ref-project-index">0{{ index+1 }}</div><div><strong>{{ project.name }}</strong></div><small>{{ project.impact }}</small></article></div></section><section><h3>Tools & Technologies</h3><div class="ref-insight-tools"><span v-for="(skill, skillIndex) in profile.skills.slice(0,8)" :key="skillIndex">{{ skill }}</span></div></section></div>
    <div class="ref-insight-bottom"><section v-bind="editAttrs('experience','experience')"><h3>Professional Experience</h3><div class="ref-insight-experience"><article v-for="job in profile.experience" :key="job.id || job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="(bullet, bulletIndex) in job.bullets" :key="bulletIndex">{{ bullet }}</li></ul></article></div></section><aside><template v-if="profile.education?.length"><h3>Education</h3><div class="ref-education"><article v-for="item in profile.education" :key="item.id || item.title"><strong>{{ item.title }}</strong><span>{{ item.place }}</span><small>{{ item.period }}</small></article></div></template><template v-if="profile.certificates?.length"><h3>Certifications</h3><div class="ref-certificates"><article v-for="item in profile.certificates" :key="item.id || item.title"><strong>{{ item.title }}</strong><span>{{ item.issuer }}</span><small>{{ item.period }}</small></article></div></template></aside></div>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'InsightGridTemplate', mixins:[referenceTemplateMixin] }
</script>