<template>
  <article class="cv-sheet ref-cv ref-next-start" :class="referenceAppearanceClasses" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <header v-bind="editAttrs('profile')"><div><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><p>Curious learner · Problem solver · Ready to make an impact</p></div><span class="ref-next-note">A Brighter<br>You Ahead</span></header>
    <div class="ref-next-body"><aside><div v-bind="editAttrs('profile')" class="ref-next-avatar"><img v-if="profile.avatar" :src="profile.avatar" alt="" :style="avatarImageStyle"><span v-else>{{ initials }}</span></div><blockquote>Eager to learn,<br>excited to build,<br>ready for what's next.</blockquote><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div><div v-bind="editAttrs('skills','skills')"><h3>Skills</h3><div class="ref-skills ref-next-skills"><span v-for="(skill, skillIndex) in profile.skills" :key="skillIndex">{{ skill }}</span></div></div></aside><main><section v-if="profile.education?.length" v-bind="editAttrs('education','education')"><h3>Education</h3><div class="ref-education"><article v-for="item in profile.education" :key="item.id || item.title"><strong>{{ item.title }}</strong><span>{{ item.place }}</span><small>{{ item.period }}</small></article></div></section><section v-bind="editAttrs('projects','projects')"><h3>Projects</h3><div class="ref-projects ref-next-projects"><article v-for="project in profile.projects.slice(0,2)" :key="project.id || project.name"><strong>{{ project.name }}</strong><p>{{ project.description }}</p><small>{{ project.impact }}</small></article></div></section><section v-bind="editAttrs('experience','experience')"><h3>Internships</h3><div class="ref-next-experience"><article v-for="job in profile.experience" :key="job.id || job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="(bullet, bulletIndex) in job.bullets" :key="bulletIndex">{{ bullet }}</li></ul></article></div></section><section><h3>Activities</h3><div class="ref-next-activities"><span>Community involvement</span><span>Team projects</span><span>Continuous learning</span></div></section></main></div><div class="ref-next-wave"><span>Small Steps<br>Big Impact ↗</span><b>Next Start · Brighter Tomorrow</b></div>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'NextStartTemplate', mixins:[referenceTemplateMixin] }
</script>