<template>
  <article class="cv-sheet ref-cv ref-people-first" :class="referenceAppearanceClasses" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <header v-bind="editAttrs('profile')"><div><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><p>{{ profile.summary }}</p></div><div class="ref-people-portrait"><div class="ref-people-avatar"><img v-if="profile.avatar" :src="profile.avatar" alt="" :style="avatarImageStyle"><span v-else>{{ initials }}</span></div><span>People<br>Build<br>Brighter<br>Workplaces ♡</span></div></header><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div>
    <div class="ref-people-body"><aside v-bind="editAttrs('skills','skills')"><h3>Key Competencies</h3><div class="ref-skills ref-people-skills"><span v-for="skill in profile.skills" :key="skill">{{ skill }}</span></div><template v-if="profile.education?.length"><h3>Education</h3><div class="ref-education"><article v-for="item in profile.education" :key="item.title"><strong>{{ item.title }}</strong><span>{{ item.place }}</span><small>{{ item.period }}</small></article></div></template></aside><main v-bind="editAttrs('experience','experience')"><h3>Professional Experience</h3><div class="ref-people-experience"><article v-for="job in profile.experience" :key="job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="bullet in job.bullets" :key="bullet">{{ bullet }}</li></ul></article></div><h3>Additional Information</h3><div class="ref-people-extra"><span v-for="language in profile.languages" :key="language">{{ language }}</span></div></main></div>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'PeopleFirstTemplate', mixins:[referenceTemplateMixin] }
</script>