<template>
  <article class="cv-sheet ref-cv ref-product-operator" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <aside class="ref-product-rail" v-bind="editAttrs('profile')"><div class="ref-product-avatar"><img v-if="profile.avatar" :src="profile.avatar" alt="" :style="avatarImageStyle"><span v-else>{{ initials }}</span></div><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2><p>{{ profile.summary }}</p><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div><div class="ref-rail-label">Core Skills</div><div class="ref-skills ref-rail-skills"><span v-for="skill in profile.skills" :key="skill">{{ skill }}</span></div></aside>
    <main class="ref-product-main"><header><h1>From Insight to Impact</h1><span>PEOPLE · PRODUCTS · PROGRESS</span></header><div class="ref-product-metrics" v-bind="editAttrs('impact','highlights')"><div v-for="item in profile.highlights" :key="item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></div><section class="ref-section" v-bind="editAttrs('experience','experience')"><h3>Experience</h3><div class="ref-product-experience"><article v-for="job in profile.experience" :key="job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="bullet in job.bullets" :key="bullet">{{ bullet }}</li></ul></article></div></section><div class="ref-product-lower"><section v-bind="editAttrs('projects','projects')"><h3>Product Highlights</h3><div class="ref-projects ref-product-highlights"><article v-for="(project,index) in profile.projects" :key="project.name"><div class="ref-project-index">0{{ index+1 }}</div><div><strong>{{ project.name }}</strong></div><small>{{ project.impact }}</small></article></div></section><section><h3>Roadmap Mindset</h3><div class="ref-roadmap"><div><b>Discover</b><span>Understand</span></div><div><b>Define</b><span>Set strategy</span></div><div><b>Deliver</b><span>Build & test</span></div><div><b>Scale</b><span>Measure impact</span></div></div></section></div></main>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'ProductOperatorTemplate', mixins:[referenceTemplateMixin] }
</script>