<template>
  <article class="cv-sheet ref-cv ref-revenue-driver" :class="referenceAppearanceClasses" :style="{ '--cv-accent': accent }" @click="handleEditRequest" @keydown="handleKeydown" @dragstart="handleDragStart" @dragover="handleDragOver" @drop="handleDrop" @dragend="handleDragEnd">
    <header><div><div v-bind="editAttrs('profile')"><h1>{{ profile.name }}</h1><h2>{{ profile.role }}</h2></div><p v-bind="editAttrs('profile', null, 'headline')">{{ profile.headline || 'Driving revenue. Building partnerships. Creating opportunity.' }}</p></div><div class="ref-sales-avatar" v-bind="editAttrs('profile')"><img v-if="profile.avatar" :src="profile.avatar" alt="" :style="avatarImageStyle"><span v-else>{{ initials }}</span></div></header><div class="ref-contact"><span>{{ profile.email }}</span><span>{{ profile.phone }}</span><span>{{ profile.location }}</span><span>{{ profile.website }}</span></div>
    <div class="ref-sales-body"><main><section v-bind="editAttrs('profile','summary')"><h3>Professional Summary</h3><p>{{ profile.summary }}</p></section><section v-bind="editAttrs('impact','highlights')"><h3>Key Performance Highlights</h3><div class="ref-sales-metrics"><div v-for="item in profile.highlights" :key="item.id || item.label"><strong>{{ item.value }}</strong><span>{{ item.label }}</span></div></div></section><section v-bind="editAttrs('experience','experience')"><h3>Professional Experience</h3><div class="ref-sales-experience"><article v-for="job in profile.experience" :key="job.id || job.role"><div class="ref-job-head"><div><strong>{{ job.role }}</strong><span>{{ job.company }}</span></div><time>{{ job.period }}</time></div><ul><li v-for="(bullet, bulletIndex) in job.bullets" :key="bulletIndex">{{ bullet }}</li></ul></article></div></section></main><aside><div v-bind="editAttrs('skills','skills')"><h3>Core Skills</h3><div class="ref-skills ref-sales-skills"><span v-for="(skill, skillIndex) in profile.skills" :key="skillIndex">{{ skill }}</span></div><h3>Selected Clients</h3><div class="ref-client-grid"><span>Microsoft</span><span>Vodafone</span><span>Sage</span><span>DELL</span><span>HSBC</span><span>Atlassian</span></div></div><blockquote v-bind="editAttrs('profile', null, 'quote')">“{{ profile.quote || "I don't just meet targets. I create momentum." }}”</blockquote></aside></div>
  </article>
</template>
<script>
import { referenceTemplateMixin } from './reference-template-mixin'
export default { name:'RevenueDriverTemplate', mixins:[referenceTemplateMixin] }
</script>