import { createApp } from 'vue'
import RootApp from './RootApp.vue'
import './styles.css'
import './enhancements.css'
import './editor.css'
import './builder-advanced.css'
import './cv-sections.css'
import './motion.css'
import './quality.css'
import './concepts/concepts.css'
import './concepts/concept-experience.css'
import './concepts/concept-polish.css'
import './styles/main.scss'

createApp(RootApp).mount('#app')
